### PR TITLE
Integrated Milvus with MetaGPT

### PR DESCRIPTION
**Pull request by Jacksonxhx**
**Features**

- add another vector database milvus into MetaGPT
    
**Feature Docs**

**Influence**

**Result**

**Other**

### CODE REVIEW

**Comment by zc277584121** [comment]
Can anyone help to review this PR? We are appreciate this MetaGPT project and hope Milvus can be integrated into it.

We found that if pymilvus dependency is added, it will conflict with some existing dependencies, so in the code, pymilvus dependency is commented out and lazy imported.

**Comment by zc277584121** [comment]
@better629

**Comment by EvensXia** [comment]
Hey, bro. I have meet the similar problem when I install it, so I have make some changes on dependency, in case that less version specified in `.whl`, my repo is [MetaGPT-simple](https://github.com/EvensXia/MetaGPT-simple) and you can install it with `python -m pip install metagpt-simple`, the pypi official link is [metagpt-simple](https://pypi.org/project/metagpt-simple/). Of course, I only do some simple test on it, if some error occur, please let me know.

**Comment by voidking** [comment]
LGTM

**Review by geekan — APPROVED** [review]

**Pull request merged**
