### PR TITLE
add  `engine` mode for azure api

### PR DESCRIPTION
**Pull request by RainFung**
Currently only `DEPLOYMENT_ID` mode is supported, `OPENAI_API_ENGINE` is added.

```
openai.ChatCompletion.acreate(
    engine="gpt-4-chatbot-ui",
    deployment_id="",
    messages=[{
        "role": "user",
        "content": "Generate a list of 20 great names for sentient cheesecakes that teach SQL"
    }],
    stream=True)
```

### CODE REVIEW

**Comment by geekan** [comment]
Corresponding test cases need to be supplemented

**Comment by RainFung** [comment]
> Corresponding test cases need to be supplemented

sry. i'll fix it soon.

**Comment by RainFung** [comment]
i found there is no test case about api `OpenAIGPTAPI` or `BaseGPTAPI`. Can you give some advice about it?

**Comment by RainFung** [comment]
> Corresponding test cases need to be supplemented

```
@pytest.mark.asyncio
async def _achat_completion(self, messages: list[dict]) -> dict:
    rsp = await self.llm.ChatCompletion.acreate(**self._cons_kwargs(messages))
    self._update_costs(rsp.get("usage"))
    return rsp

async def test_llm_acompletion(llm):
    hello_msg = [{'role': 'user', 'content': 'hello'}]
    assert len(await llm.acompletion(hello_msg)) > 0
    assert len(await llm.acompletion_batch([hello_msg])) > 0
    assert len(await llm.acompletion_batch_text([hello_msg])) > 0
```

kwargs has been tested in the test_llm_acompletion function via `acompletion`. Is there no need to add an additional test?

**Comment by voidking** [comment]
If didn't config `OPENAI_API_ENGINE`, just use `DEPLOYMENT_ID`, then the error will occur.
tenacity.RetryError: RetryError[<Future at 0x12578f520 state=finished raised TypeError>]

**Comment by RainFung** [comment]
> If didn't config `OPENAI_API_ENGINE`, just use `DEPLOYMENT_ID`, then the error will occur. tenacity.RetryError: RetryError[<Future at 0x12578f520 state=finished raised TypeError>]

fixed. I added relevant boundary detection to my code.

**Comment by voidking** [comment]
LGTM

**Comment by voidking** [comment]
Yes, the error is disappear.
Could you give a example configuration? I didn't understand the relationship between DEPLOYMENT_ID and OPENAI_API_ENGINE.

**Comment by voidking** [comment]
image
This is a deployment. And what is a engine? `engine == model` ?

**Comment by RainFung** [comment]
> it's `Deployment Name`.

image
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions

**Comment by stellaHSR** [comment]
LGTM

**Comment by stellaHSR** [comment]
LGTM

**Comment by stellaHSR** [comment]
Hi, are you interested in joining the dev group?

**Comment by RainFung** [comment]
> Hi, are you interested in joining the dev group?

yeah, You can contact me via QQ account or WeChat.  **_409908131_**
by the way. It's better to squash commits before merging the code to main branch.

**Pull request merged**
