### PR TITLE
Added a callback mechanism for capturing logs and updates during DI execution. Can be extended to other roles too. 

### PR DESCRIPTION
**Pull request by krish240574**
**Features**

Logs capture and log update mechanism for the DataInterpreter, Role, Team and Env classes, which can get displayed on a webpage using websockets. 

- xx
- yy
    
**Feature Docs**

**Influence**

**Result**

**Other**

### CODE REVIEW

**Comment by davidleon** [comment]
team.py change contains space tab formatting change. Better retain the original formatting style. and minimize formatting change. Any example of using the gui_callback available? a small example would be great to illustrate how this enriches the frontend experience.

**Comment by krish240574** [comment]
Sorry about that, David, I'll change back to spaces - let me put up an example of the usage , in a bit.  Thanks for pointing that out.

**Comment by krish240574** [comment]
@davidleon - have fixed the formatting in team.py and added an example inside examples/gui_update_example.py.

**Comment by krish240574** [comment]
@davidleon - updated the user level example in examples/gui_update_example.py - better updates, better handling of the messages. Do take a look.

**Pull request closed without merging**
