### PR TITLE
feature: added configuration files  for gitpod

### PR DESCRIPTION
**Pull request by PentesterPriyanshu**
added .gitpod.yml  file for gitpod users this is missing so i added it

### CODE REVIEW

**Comment by PentesterPriyanshu** [comment]
@stellaHSR  merge this pr

**Comment by voidking** [comment]
I think your purpose is to automatically set up the environment in gitpod.
So there are two issues to note:
1. gitpod default python version is 3.12 which is not suitable for MetaGPT. You should change it to python3.9 or python3.10 in `.gitpod.Dockefile`
2. The init command of MetaGPT is `pip install -e.` .

**Comment by PentesterPriyanshu** [comment]
> I think your purpose is to automatically set up the environment in gitpod. So there are two issues to note:
> 
>     1. gitpod default python version is 3.12 which is not suitable for MetaGPT. You should change it to python3.9 or python3.10 in `.gitpod.Dockefile`
> 
>     2. The init command of MetaGPT is `pip install -e.` .

thanks for your reply i am now commiting all changes as you want

**Comment by PentesterPriyanshu** [comment]
@voidking    now you can merge it ,

**Comment by geekan** [comment]
Please resolve all conflicts and Review comments

**Pull request closed without merging**
