### PR TITLE
Fix: ImportError: cannot import name 'ProductManager' from 'metagpt.roles'

### PR DESCRIPTION
**Pull request by denniseilander**
Fixes issue https://github.com/geekan/MetaGPT/issues/219

### CODE REVIEW

**Review by dyaskur — APPROVED** [review]
I can confirm this is worked and fix #219

**Comment by voidking** [comment]
LGTM

**Comment by asher-gtriip** [comment]
thanks @denniseilander !, found this issue while testing but didn't have access to my github

**Comment by denniseilander** [comment]
@asher-gtriip no problem! I saw you ticket and hoped to see te solution (which I later found in your post), but the fix was easier than I thought. Hopefully this can be merged soon.

**Comment by nicolasdec** [comment]
Worked for me! Thank you.

**Pull request merged**
