### PR TITLE
Adding a Dockerfile for docker implementation

### PR DESCRIPTION
**Pull request by sablin39**
I wrote a Dockerfile that can use the same config as the host machine and stores the results in the host as well.

### CODE REVIEW

**Comment by jmanhype** [comment]
Does this work?

**Comment by jmanhype** [comment]
Working?

**Comment by geekan** [comment]
Requires optimization. Minimize the size of the image as much as possible, and try to add the conditional judgment for selecting the source.

**Comment by sablin39** [comment]
I add some cache removal commands to reduce the size of the image. Moreover, I've push it to dockerhub so you can simply pull and try the image, have fun :)

**Pull request merged**
