### PR TITLE
bugfix: At least 8 rounds are required to run all QA actions

### PR DESCRIPTION
**Pull request by voidking**
**Bugfix**
If --run-tests is enabled, at least 8 rounds are required to run all QA actions.
https://discord.com/channels/1125308739348594758/1301596320561238016

### CODE REVIEW

**Comment by iorisa** [comment]
LGTM

**Comment by stellaHSR** [comment]
I suggest to add unit tests for this, in  https://github.com/geekan/MetaGPT/blob/main/tests/metagpt/test_software_company.py

**Comment by stellaHSR** [comment]
I suggest adding unit tests for QA engineer role in test_software_company.py. Specifically:

1. Test coverage needed:
- QA role initialization and presence in team
- Test case generation functionality
- CLI parameters handling (--run-tests, --n-round)
- Integration with different round numbers

2. Suggested test cases:
```python
@pytest.mark.asyncio
async def test_qa_engineer_role():
    company = Team()
    history = await company.run(
        idea="Write a calculator",
        run_tests=True,
        n_round=8
    )
    assert any(role.name == "QAEngineer" for role in company.members)
    assert any("test case" in str(msg.content) for msg in history)

def test_cli_with_qa_tests():
    args = ["Make a calculator", "--run-tests", "--n-round=8"]
    result = runner.invoke(app, args)
    assert "test" in result.output.lower()
    assert result.exit_code == 0

**Comment by stellaHSR** [comment]
LGTM

**Review by geekan — APPROVED** [review]

**Pull request merged**
